### ISSUE TITLE
ValueError: Input 0 is incompatible with layer model: expected shape=(None, 1733, 1), found shape=(None, 305, 1)

### ISSUE THREAD

**Issue by lanasushko** [CSU-KangHu/NeuralTE#1]
Hello!

First of all, thanks for developing NeuralTE.
I was trying to run Classifier.py using the NeuralTE/demo/test.fa dataset exactly as described in "Demo data" README section. 

python /home/NeuralTE/src/Classifier.py --data /home/NeuralTE/demo/test.fa --outdir /home/NeuralTE_test/test --model_path /home/NeuralTE/models/NeuralTE_model.h5 --thread 10

I installed NeuralTE on a linux machine as specified in "Option 1. Run with Conda"

The outputs in the outdir are: 
domain  minority  segLTR2intactLTR.map  temp  test.fa  test.fa.domain

I am getting the following error:
ValueError: Input 0 is incompatible with layer model: expected shape=(None, 1733, 1), found shape=(None, 305, 1)

Is there anything I can do about this error?
Thanks!

**Comment by CSU-KangHu** [comment]
Hi @lanasushko,
Thank you for bringing this to our attention! The error occurred due to the inconsistency between the feature counts of the pre-trained model and the features reconstructed from the test set. We recently made modifications to the code, but forgot to replace it with the latest pre-trained model. We have now updated to the latest pre-trained model, and updating to the latest code should resolve this issue. 
If you encounter any further issues while using NeuralTE, please don't hesitate to let us know.
